const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('vehicles.db');

db.serialize(() => {
    db.run("CREATE TABLE vehicles (id INTEGER PRIMARY KEY AUTOINCREMENT, lot TEXT, vin TEXT, model TEXT, year INTEGER, shipper TEXT, point_of_loading TEXT, towing_company TEXT, client TEXT, agent TEXT, port TEXT, client_group TEXT, mix INTEGER, title_status TEXT, title_number TEXT, title_state TEXT, storage_driver INTEGER, storage_other INTEGER, auction TEXT, buyer TEXT, color TEXT, left_auction TEXT, delivery TEXT, payment INTEGER, paid INTEGER, company_notes TEXT, customer_notes TEXT)");

    db.run("INSERT INTO vehicles (lot, vin, model, year, shipper, point_of_loading, towing_company, client, agent, port, client_group, mix, title_status, title_number, title_state, storage_driver, storage_other, auction, buyer, color, left_auction, delivery, payment, paid, company_notes, customer_notes) VALUES ('67344485', '4Y1SL65848Z411439', 'TOYOTA RAV4', 2020, 'Janis', 'NY', 'Morelli Logistics', 'W8 Shipping', 'Abdulharat Al Laminat', 'Poti', '', 1, 'YES', '288400677', 'OH', 0, 0, 'Copart', 'G&G', 'white', '2024-09-17', '2024-09-17', 150, 1, '', '')");
    db.run("INSERT INTO vehicles (lot, vin, model, year, shipper, point_of_loading, towing_company, client, agent, port, client_group, mix, title_status, title_number, title_state, storage_driver, storage_other, auction, buyer, color, left_auction, delivery, payment, paid, company_notes, customer_notes) VALUES ('53999212', '3JSTL53448Z434422', 'NISSAN ALTIMA', 2013, 'Janis', 'NY', 'Morelli Logistics', 'Jabon Jabilat', '', 'Jebel Ali', '', 1, '', '', '', 0, 0, 'Copart', 'Verica', 'black', '2024-09-17', '2024-09-17', 150, 0, '', '')");
    db.run("INSERT INTO vehicles (lot, vin, model, year, shipper, point_of_loading, towing_company, client, agent, port, client_group, mix, title_status, title_number, title_state, storage_driver, storage_other, auction, buyer, color, left_auction, delivery, payment, paid, company_notes, customer_notes) VALUES ('45774789', '7PDA5344FF0054411', 'JEEP COMPASS', 2018, 'Janis', 'NY', 'No Stress Transportation', 'Jabon Jabilat', '', 'Salalah', '', 1, '', '', '', 0, 0, 'IAAI', '', 'green', '2024-09-17', '', 150, 0, '', '')");
    db.run("INSERT INTO vehicles (lot, vin, model, year, shipper, point_of_loading, towing_company, client, agent, port, client_group, mix, title_status, title_number, title_state, storage_driver, storage_other, auction, buyer, color, left_auction, delivery, payment, paid, company_notes, customer_notes) VALUES ('61142781', '1FTPS24L8WHC09604', 'TOYOTA CAMRY', 2024, 'Janis', 'NY', 'LoadX LLC', 'Majdi Bin Said', '', 'Sohar', 'Majdi Bin Said', 0, '', '', '', 0, 0, 'Copart', '', 'yellow', '', '', 300, 0, '', '')");
    db.run("INSERT INTO vehicles (lot, vin, model, year, shipper, point_of_loading, towing_company, client, agent, port, client_group, mix, title_status, title_number, title_state, storage_driver, storage_other, auction, buyer, color, left_auction, delivery, payment, paid, company_notes, customer_notes) VALUES ('78999989', '3GYT3MEF0D0019421', 'BMW X5', 2017, 'Janis', 'NY', 'LoadX LLC', 'King Cars', 'Galaxy Used Cars', 'Salalah', '', 0, '', '', '', 0, 0, 'Copart', 'Prakticars', 'black', '', '', 280, 0, '', '')");
    db.run("INSERT INTO vehicles (lot, vin, model, year, shipper, point_of_loading, towing_company, client, agent, port, client_group, mix, title_status, title_number, title_state, storage_driver, storage_other, auction, buyer, color, left_auction, delivery, payment, paid, company_notes, customer_notes) VALUES ('45221580', '1G6KY549X3U283448', 'LEXUS RX 250', 2010, 'Janis', 'NY', 'DDL Logistics LLC', '', 'USAUSEDCARS LD', 'Sohar', '', 0, '', '', '', 0, 0, 'IAAI', 'Champion Used Cars', 'black', '', '', 100, 0, '', '')");
});

db.close();